### ISSUE TITLE
labeling and classes of images

### ISSUE THREAD

**Issue by Tortoise17** [Alibaba-MIIL/ImageNet21K#42]
I have seen your code very nice. I want to ask that  how to get the labeling and classes for the images  / folders?

**Comment by mrT23** [comment]
https://github.com/Alibaba-MIIL/ImageNet21K/issues/12

**Comment by Tortoise17** [comment]
@mrT23 Thank you. Yes, I know. Now the next question is that how to see the hierarchical tree  using this model because I want to see the classes before I use the dataset. Can I see the classes with the importing model. If you can guide me.

**Comment by mrT23** [comment]
thoroughly review the content of the file 
`'imagenet21k_miil_tree.pth'`
and the class that process it
```
args.tree_path = filename
semantic_softmax_processor = ImageNet21kSemanticSoftmax(args)
```
https://github.com/Alibaba-MIIL/ImageNet21K/blob/9dd5725438785413832303b5626eaa4bb5dc0535/src_files/semantic/semantics.py#L14

it contains all the information on ImageNet21K, including the parents of each class

**Comment by Tortoise17** [comment]
@mrT23 Thank you. Really nice help. Can I export it or visualize before using these classes using this code?

**Comment by mrT23** [comment]
a simple breakpoint can get you a long way...

![image](https://user-images.githubusercontent.com/21198860/130330942-b9e26a08-72ef-466f-a489-3b54ddfcbc60.png)

'semantic_softmax_processor.class_tree_list'
contains all the parents of each class

**Comment by Tortoise17** [comment]
I added here as breaking point

```
class ImageNet21kSemanticSoftmax:
    def __init__(self, args):
        self.args = args
        self.tree = torch.load(args.tree_path)
        self.class_tree_list = self.tree['class_tree_list']
        self.class_names = np.array(list(self.tree['class_description'].values()))
        self.max_normalization_factor = 2e1
        num_classes = len(self.class_tree_list)
        self.class_depth = torch.zeros(num_classes)
        for i in range(num_classes):
            self.class_depth[i] = len(self.class_tree_list[i]) - 1
        max_depth = int(torch.max(self.class_depth).item())

        # process semantic relations
        hist_tree = torch.histc(self.class_depth, bins=max_depth + 1, min=0, max=max_depth).int()
        ind_list = []
        class_names_ind_list = []
        hirarchy_level_list = []
        cls = torch.tensor(np.arange(num_classes))
        for i in range(max_depth):
            if hist_tree[i] > 1:
                hirarchy_level_list.append(i)
                ind_list.append(cls[self.class_depth == i].long())
                class_names_ind_list.append(self.class_names[ind_list[-1]])
        self.hierarchy_indices_list = ind_list
        self.hirarchy_level_list = hirarchy_level_list
        self.class_names_ind_list = class_names_ind_list

        **if not os.path.isfile(filename):
            urllib.request.urlretrive(url, filename)
        args = Namespace()
        args.tree_path = filename
        semantic_softmax_processor = ImageNet21SemanticSoftmax(args)
        print("done")**

        # calcuilating normalization array
        self.normalization_factor_list = torch.zeros_like(hist_tree)
        self.normalization_factor_list[-1] = hist_tree[-1]
        for i in range(max_depth):
            self.normalization_factor_list[i] = torch.sum(hist_tree[i:], dim=0)
        self.normalization_factor_list = self.normalization_factor_list[0] / self.normalization_factor_list
        if self.max_normalization_factor:
            self.normalization_factor_list.clamp_(max=self.max_normalization_factor)
```

it is throwing error. 

```
(image) [benny@pro ImageNet21K-main]$ python train_semantic_softmax.py --batch_size=4 --data_path=../extract_i --model_name=mobilenetv3_large_100 --model_path=/scratch/local/user/imagenet21k_miil_tree_fall11.pth --epochs=1
creating model mobilenetv3_large_100...
Traceback (most recent call last):
  File "train_semantic_softmax.py", line 126, in <module>
    main()
  File "train_semantic_softmax.py", line 53, in main
    model = create_model(args).cuda()
  File "/scratch/local/user/ImageNet21K-main/src_files/models/utils/factory.py", line 55, in create_model
    model = load_model_weights(model, args.model_path)
  File "/scratch/local/user/ImageNet21K-main/src_files/models/utils/factory.py", line 15, in load_model_weights
    if key in state['state_dict']:
KeyError: 'state_dict'
```

This error is even without change of or addition of those lines to print out the classes. 

Can you guide me. Why this error or what this error means, 
also, please correct me if my breakdown point is wrong to print out labels.

**Comment by cs-heibao** [comment]
try to `import os ` in the script

**Comment by Tortoise17** [comment]
@mrT23 @cs-heibao  thank you. Now 
`NameError: name 'filename' is not defined`

**Comment by mrT23** [comment]
@Tortoise17 debug it slowly and thoroughly. you have local problems.
follow the script as an helper
https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/visualize_detector.py
'filename' is defined in the code there

```
############### Downloading metadata ##############
print("downloading metadata...")
url, filename = (
    "https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/resources/fall11/imagenet21k_miil_tree.pth",
    "imagenet21k_miil_tree.pth")
if not os.path.isfile(filename):
    urllib.request.urlretrieve(url, filename)
args = Namespace()
args.tree_path = filename
semantic_softmax_processor = ImageNet21kSemanticSoftmax(args)
print("done")
```
