### ISSUE TITLE
cant run visualize_detector.py

### ISSUE THREAD

**Issue by jaffe-fly** [Alibaba-MIIL/ImageNet21K#6]
https://github.com/Alibaba-MIIL/ImageNet21K/blob/72c822a7a30290f078a2611139a1f0bcdb668606/visualize_detector.py#L25

error:

Unknown model (vit_base_patch16_224_miil_in21k)

how to run with my own wight

**Comment by Stephen-Hao** [comment]
![image](https://user-images.githubusercontent.com/35420905/118611196-27ef6800-b7ef-11eb-8e4c-3e3bf185908d.png)
@In Pytorch Image models you can find it, Try to update the timm?

**Comment by mrT23** [comment]
you are right @Stephen-Hao 
@jaffe-fly: update to latest timm version

```
pip uninstall timm
pip install git+https://github.com/rwightman/pytorch-image-models.git
```

**Comment by jaffe-fly** [comment]
I am training on my 17flowers dataset  and save checkpoint,.when i predict , its error!!
```
Traceback (most recent call last):
  File "plugin_test.py", line 28, in <module>
    ynet.predict(data)
  File "/home/wangzf/ImageNetClassify/server/plugins/imagenet/ImageNet.py", line 118, in predict
    semantic_logit_list = self.semantic_softmax_processor.split_logits_to_semantic_logits(logits)
  File "/home/wangzf/ImageNetClassify/server/plugins/imagenet/semantic/semantics.py", line 50, in split_logits_to_semantic_logits
    logits_i = logits[:, ind]
IndexError: index 40 is out of bounds for dimension 0 with size 17
```
My code
```

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
semantic_softmax_processor = ImageNet21kSemanticSoftmax(imagenet_path)

labels_to_idx = {'黄水仙': '0', '雪花莲': '1', '百合谷': '2', '蓝铃': '3', '番红花': '4',
                         '鸢尾花': '5', '倾斜': '6', '郁金香': '7', '贝母': '8', '向日葵': '9', '雏菊': '10',
                         '小马队脚': '11', '蒲公英': '12', '奶牛纤维': '13', '毛茛属植物': '14', '迎风': '15', '三色堇': '16'}

model = timm.create_model('mobilenetv3_large_100',pretrained=False, num_classes=len(labels_to_idx),checkpoint_path='/tmp/model.alphamind.h5')
model.eval()
config = resolve_data_config({}, model=model)
image_path ='1.jpg'
img = Image.open(image_path).convert('RGB')
transform = create_transform(**self.config)
tensor = transform(img).unsqueeze(0)  # transform and add batch dimension
logger.info("doing semantic infernce...")
labels = []
with torch.no_grad():
    logits = model(tensor)
    semantic_logit_list = semantic_softmax_processor.split_logits_to_semantic_logits(logits)
    # scanning hirarchy_level_list
    for i in range(len(semantic_logit_list)):
        logits_i = semantic_logit_list[i]

        # generate probs
        probabilities = torch.nn.functional.softmax(logits_i[0], dim=0)
        top1_prob, top1_id = torch.topk(probabilities, 1)

        if top1_prob > 0.5:
            top_class_number = semantic_softmax_processor.hierarchy_indices_list[i][top1_id[0]]
            top_class_name = semantic_softmax_processor.tree['class_list'][top_class_number]
            top_class_description = semantic_softmax_processor.tree['class_description'][top_class_name]
            labels.append(top_class_description)

logger.info("labels found {}.".format(labels))
```
Where to change???

**Comment by mrT23** [comment]
@jaffe-fly 
you can't use 'visualize_detector.py' file to visualize a detector on your own dataset
it uses the specific hierarchy structure of imagenet-21k.

for your dataset, you can predict the top1 class for each image
```
  # generate probs
  probabilities = torch.nn.functional.softmax(logits, dim=0)
  top1_prob, top1_id = torch.topk(probabilities, 1)
```

**Comment by jaffe-fly** [comment]
<img width="804" alt="微信截图_20210519164107" src="https://user-images.githubusercontent.com/49515380/118782790-0bbbfb80-b8c1-11eb-979a-6d87b63e4c50.png">



it seems wrong!

**Comment by mrT23** [comment]
i am not sure what's the problem, maybe the dim should be different, or you should do 
`softmax(logits[0])`
align you dims by finding out what is: 
`print(logits.shape)`

anyway, after you properly initialize the model on your transfer learning task, it's a standard timm model.
an example of general inference of timm model can be found in:
https://rwightman.github.io/pytorch-image-models/models/mobilenet-v3/

**Comment by batselem** [comment]
I got the same problem.
Tried following 
```
pip uninstall timm
pip install git+https://github.com/rwightman/pytorch-image-models.git
```
but still error exists

**Comment by jaffe-fly** [comment]
thanks
